{"name": "test_xfail_expected_failure", "status": "skipped", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <test_demo.TestShoppingTrolley object at 0x03FD93D0>\n\n    @pytest.mark.xfail(condition=lambda: True, reason='this test is expecting failure')\n    def test_xfail_expected_failure(self):\n        \"\"\"this test is an xfail that will be marked as expected failure\"\"\"\n>       assert False\nE       assert False\n\ntest_demo.py:39: AssertionError"}, "description": "this test is an xfail that will be marked as expected failure", "start": 1576479799711, "stop": 1576479799712, "uuid": "64ac9388-1442-495b-9208-978c66a529a0", "historyId": "56ba11e19ed4d118f2916255aa9e2ef4", "fullName": "test_demo.TestShoppingTrolley#test_xfail_expected_failure", "labels": [{"name": "feature", "value": "购物车功能"}, {"name": "parentSuite"}, {"name": "suite", "value": "test_demo"}, {"name": "subSuite", "value": "TestShoppingTrolley"}, {"name": "host", "value": "6CR6110JFK"}, {"name": "thread", "value": "5928-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_demo"}]}